language: python
python:
  - "2.7"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"

# command to run tests
script:
    nosetests -v --with-coverage --cover-package=archiver --cover-package=pyi_updater

after_success:
  coveralls
