language: python
python:
  - "2.7"

# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls pytest pytest-cov pytest-xdist"

# command to run tests
script:
    py.test -v --cov src/pyi_updater -n 1

after_success:
  coveralls
